const actionTypes = {
    GET_USERS: 'GET_USERS',
    POST_USER:'POST_USER',
    DELETE_USER:'DELETE_USER',
    UPDATE_USER:'UPDATE_USER',

    UI_CONFIRM_STATE: 'UI_CONFIRM_STATE',
    UI_MODAL_STATE: 'UI_MODAL_STATE',
}

export { actionTypes }